"""add listing url

Revision ID: a1edd76a2259
Revises: b3b63a462593
Create Date: 2019-09-10 23:07:49.741927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1edd76a2259'
down_revision = 'b3b63a462593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('link_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'link_url')
    # ### end Alembic commands ###
